//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Error()
        {
            this.StatusErrors = new HashSet<StatusError>();
            this.StatusErrors1 = new HashSet<StatusError>();
        }
    
        public int ErrorNumber { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<decimal> TreatmentHours { get; set; }
        public string Description { get; set; }
        public string ErrorType { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> MoldID { get; set; }
        public byte[] ErrorPicture { get; set; }
        public Nullable<int> LeadingTechnicianID { get; set; }
    
        public virtual Mold Mold { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Technician Technician { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusError> StatusErrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusError> StatusErrors1 { get; set; }
        public virtual MoldRoomTechnician MoldRoomTechnician { get; set; }
    }
}
