//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InjectionTechnician
    {
        public int EmployeeNumber { get; set; }
        public Nullable<int> LocationCode { get; set; }
    
        public virtual Technician Technician { get; set; }
        public virtual Location Location { get; set; }
    }
}
