//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetafimDbContext : DbContext
    {
        public NetafimDbContext()
            : base("name=NetafimDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<InjectionTechnician> InjectionTechnicians { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Mold> Molds { get; set; }
        public virtual DbSet<MoldRoomTechnician> MoldRoomTechnicians { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<SchedulingConstraint> SchedulingConstraints { get; set; }
        public virtual DbSet<StatusError> StatusErrors { get; set; }
        public virtual DbSet<StatusErrorStageEnum> StatusErrorStageEnums { get; set; }
        public virtual DbSet<Technician> Technicians { get; set; }
    }
}
