//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulingConstraint
    {
        public int ConstraintNumber { get; set; }
        public System.DateTime ConstraintDate { get; set; }
        public System.TimeSpan ConstraintStartHour { get; set; }
        public System.TimeSpan ConstraintEndHour { get; set; }
        public string Description { get; set; }
        public int TechnicianID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
