//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusError
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusError()
        {
            this.Errors = new HashSet<Error>();
        }
    
        public int ErrorStatusID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> MoldRoomTechnicianNumber { get; set; }
        public Nullable<int> ErrorNumber { get; set; }
        public string StatusType { get; set; }
    
        public virtual Error Error { get; set; }
        public virtual MoldRoomTechnician MoldRoomTechnician { get; set; }
        public virtual StatusErrorStageEnum StatusErrorStageEnum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Error> Errors { get; set; }
    }
}
